language: java
sudo: false
os: linux
jdk: openjdk11
script:
  - jdk_switcher use openjdk11
  - export JAVA_HOME=$HOME/openjdk11
  - $TRAVIS_BUILD_DIR/install-jdk.sh --install openjdk11 --target $JAVA_HOME

cache:
  directories:
    - $HOME/.m2

env:
  - PROJECTS_TO_BUILD: "!diozero-imu-visualiser"

install: true
script: mvn --projects '!diozero-imu-visualiser' clean compile package install
#script: mvn ${MAVEN_OPTS} clean compile package install
#script: mvn --projects='${PROJECTS_TO_BUILD}' clean compile package install

#deploy:
#  on:
#    all-branches: true
#  provider: bintray
#  file: distribution/bintray.json
#  user: mattjlewis
#  key: $BINTRAY_API_KEY
