site_name: diozero
site_url: https://github.diozero.com
site_description: Device I/O abstraction library written in Java
site_author: Matt Lewis

repo_url: https://github.com/mattjlewis/diozero
docs_dir: rtd/docs

pages:
- Home: 'index.md'
- Create Your Own Application: 'Application.md'
- Remote Control: 'RemoteControl.md'
- Devices:
    - 'API': 'API.md'
    - 'Input Devices': 'InputDevices.md'
    - 'Output Devices': 'OutputDevices.md'
    - 'Expansion Boards': 'ExpansionBoards.md'
    - 'Motor Control': 'MotorControl.md'
    - 'Sensor Components': 'SensorComponents.md'
    - 'LCD Displays': 'LCDDisplays.md'
    - 'LED Strips': 'LEDStrips.md'
    - 'IMU Devices': 'IMUDevices.md'
- Providers: 'Providers.md'
- Release: 'RELEASE.md'
- License: 'license.md'

copyright: Copyright &copy; 2020 Matt Lewis
google_analytics: ['UA-73764647-1', 'rtd.diozero.com']
# theme: sphinx_rtd_theme
theme: readthedocs
markdown_extensions:
- admonition
- attr_list
- def_list
